#!/bin/bash

echo "=== SOLUÇÃO FINAL SEM SUDO - GIT PUSH ==="
echo ""

# Método alternativo sem sudo
echo "MÉTODO 1: Limpeza sem sudo"
echo "========================="
echo ""
echo "1. Copie e cole no Shell do Replit:"
echo ""
echo "# Tentar remover locks (pode dar erro, mas continue)"
echo "rm -f .git/index.lock 2>/dev/null || true"
echo "rm -f .git/config.lock 2>/dev/null || true"
echo ""
echo "# Configurar usuário Git local (não global)"
echo "git config user.name \"mxttheuzs\""
echo "git config user.email \"mathildiscord@gmail.com\""
echo ""
echo "# Limpar e reconfigurar repositório remoto"
echo "git remote remove origin 2>/dev/null || true"
echo "git remote add origin https://github.com/mxttheuzs/livro-colorir-cristaos.git"
echo ""
echo "# Verificar configuração"
echo "git remote -v"
echo ""
echo "# Forçar desbloqueio do índice Git"
echo "git reset --mixed HEAD"
echo ""
echo "# Adicionar arquivos"
echo "git add -A"
echo ""
echo "# Fazer commit"
echo "git commit -m \"Push projeto livros colorir cristãos - $(date '+%Y-%m-%d %H:%M')\""
echo ""
echo "# Push com token"
echo "git push https://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@github.com/mxttheuzs/livro-colorir-cristaos.git main --force"
echo ""
echo ""

echo "MÉTODO 2: Uma linha completa"
echo "=========================="
echo ""
echo "Cole tudo de uma vez:"
echo ""
cat << 'EOF'
rm -f .git/index.lock .git/config.lock 2>/dev/null; git config user.name "mxttheuzs"; git config user.email "mathildiscord@gmail.com"; git remote remove origin 2>/dev/null; git remote add origin https://github.com/mxttheuzs/livro-colorir-cristaos.git; git reset --mixed HEAD; git add -A; git commit -m "Push projeto livros colorir $(date)"; git push https://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@github.com/mxttheuzs/livro-colorir-cristaos.git main --force
EOF
echo ""
echo ""

echo "MÉTODO 3: Upload Manual (Mais Confiável)"
echo "======================================="
echo ""
echo "1. No Replit, clique em 'Files' no painel esquerdo"
echo "2. Clique nos 3 pontos (...) no topo do painel Files"
echo "3. Selecione 'Download as zip'"
echo "4. Vá para: https://github.com/mxttheuzs/livro-colorir-cristaos"
echo "5. Clique 'Add file' → 'Upload files'"
echo "6. Arraste todos os arquivos do zip baixado"
echo "7. Escreva: 'Atualização completa projeto'"
echo "8. Clique 'Commit changes'"
echo ""
echo "Token para login: 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"